import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface TokenStats {
  symbol: string;
  name: string;
  totalHolders: number;
  realHolders: number;
  whaleCount: number;
  strongCount: number;
  activeCount: number;
  dustCount: number;
  dustPercentage: number;
  healthScore: number;
  healthGrade: string;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { tokenStats, returnType = 'url' } = await req.json() as { tokenStats: TokenStats; returnType?: 'url' | 'base64' };

    console.log('Generating share card image for:', tokenStats.symbol);

    // Use Lovable AI to generate a professional share card image
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) {
      throw new Error("LOVABLE_API_KEY is not configured");
    }

    const prompt = `Create a professional, sleek social media share card (1200x628 pixels, Twitter/OG format) for a cryptocurrency holder analysis report.

Design Requirements:
- Dark theme background with subtle gradients (dark grays, blacks)
- Modern, clean fintech aesthetic
- Left side: Large hero numbers showing "${tokenStats.totalHolders.toLocaleString()}" total wallets with arrow pointing down to "${tokenStats.realHolders.toLocaleString()}" real holders in bright green
- Include text "${tokenStats.dustPercentage}% are dust wallets" in amber/orange
- Right side: Health grade badge showing "${tokenStats.healthGrade}" (${tokenStats.healthScore}/100) - use ${tokenStats.healthGrade.startsWith('A') ? 'green' : tokenStats.healthGrade.startsWith('B') ? 'blue' : tokenStats.healthGrade.startsWith('C') ? 'amber' : 'red'} color
- Bottom: "blackbox.farm/holders" branding and "Free Holder Analysis Report"
- Small token badge showing "$${tokenStats.symbol}" in corner
- Include visual bars or icons for: ${tokenStats.whaleCount} Whales 🐋, ${tokenStats.strongCount} Strong 💪, ${tokenStats.activeCount} Active 🌱
- Professional, trustworthy, data-driven look
- NO placeholder text, all data should be the actual numbers provided
- Ultra high resolution, crisp text`;

    console.log('Calling Lovable AI for image generation...');

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash-image-preview",
        messages: [
          {
            role: "user",
            content: prompt
          }
        ],
        modalities: ["image", "text"]
      })
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error("AI gateway error:", response.status, errorText);
      
      if (response.status === 429) {
        return new Response(JSON.stringify({ error: "Rate limit exceeded, please try again later" }), {
          status: 429,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      if (response.status === 402) {
        return new Response(JSON.stringify({ error: "AI credits depleted" }), {
          status: 402,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      throw new Error(`AI gateway error: ${response.status}`);
    }

    const aiData = await response.json();
    console.log('AI response received');

    const imageBase64 = aiData.choices?.[0]?.message?.images?.[0]?.image_url?.url;
    
    if (!imageBase64) {
      console.error('No image in AI response:', JSON.stringify(aiData).slice(0, 500));
      throw new Error("No image generated by AI");
    }

    // If just returning base64, do so
    if (returnType === 'base64') {
      return new Response(JSON.stringify({ 
        success: true,
        imageBase64 
      }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Upload to Supabase storage for sharing
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Convert base64 to blob
    const base64Data = imageBase64.replace(/^data:image\/\w+;base64,/, '');
    const imageBytes = Uint8Array.from(atob(base64Data), c => c.charCodeAt(0));

    const fileName = `share-cards/${tokenStats.symbol.toLowerCase()}-${Date.now()}.png`;
    
    const { data: uploadData, error: uploadError } = await supabase.storage
      .from('public-assets')
      .upload(fileName, imageBytes, {
        contentType: 'image/png',
        upsert: true
      });

    if (uploadError) {
      console.error('Upload error:', uploadError);
      // Return base64 as fallback
      return new Response(JSON.stringify({ 
        success: true,
        imageBase64,
        note: 'Could not upload to storage, returning base64'
      }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { data: publicUrl } = supabase.storage
      .from('public-assets')
      .getPublicUrl(fileName);

    console.log('Image uploaded successfully:', publicUrl.publicUrl);

    return new Response(JSON.stringify({ 
      success: true,
      imageUrl: publicUrl.publicUrl,
      imageBase64
    }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });

  } catch (error) {
    console.error('Error generating share card:', error);
    return new Response(JSON.stringify({ 
      error: error instanceof Error ? error.message : 'Unknown error' 
    }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
