import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface TokenStats {
  symbol: string;
  name: string;
  tokenAddress?: string;
  totalHolders: number;
  realHolders: number;
  whaleCount: number;
  strongCount: number;
  activeCount: number;
  dustCount: number;
  dustPercentage: number;
  healthScore: number;
  healthGrade: string;
}

function escapeHtml(s: string) {
  return s
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { tokenStats, returnType = 'url' } = await req.json() as { tokenStats: TokenStats; returnType?: 'url' | 'base64' };

    console.log('Generating share card image for:', tokenStats.symbol);

    // Use Lovable AI to generate a professional share card image
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) {
      throw new Error("LOVABLE_API_KEY is not configured");
    }

    // Truncate CA for display
    const truncateCA = (addr: string) => addr && addr.length > 12 ? `${addr.slice(0, 6)}...${addr.slice(-4)}` : addr || '';
    const displayCA = truncateCA(tokenStats.tokenAddress || '');

    const prompt = `Create a professional social media share card (1200x628 pixels) for a crypto holder analysis.

CRITICAL - HIGH CONTRAST TEXT REQUIREMENTS:
- Background: SOLID DARK (#0a0a0f or similar very dark color, NOT complex gradients that reduce readability)
- ALL text must be HIGHLY READABLE with strong contrast
- Use BOLD WHITE text for important numbers
- Use BRIGHT NEON GREEN (#00ff88) for key metrics

LAYOUT:
- TOP RIGHT: "$${tokenStats.symbol}" in LARGE BOLD WHITE (32px+), below it "CA:${displayCA}" in LIGHT GRAY (#aaaaaa, 16px)
- LEFT SIDE HERO STATS (large, clear, readable):
  * "${tokenStats.totalHolders.toLocaleString()}" in HUGE BOLD WHITE text (72px+) with label "Total Wallets" below
  * Arrow down to "${tokenStats.realHolders.toLocaleString()}" in BRIGHT GREEN (#00ff88, 48px+) with "Real Holders" label
  * "${tokenStats.dustPercentage}% Dust" in ORANGE/AMBER (#ffaa00)
- RIGHT SIDE: Compact grade badge "${tokenStats.healthGrade}" (small, ${tokenStats.healthGrade.startsWith('A') ? 'green' : tokenStats.healthGrade.startsWith('B') ? 'blue' : 'amber'}, with ${tokenStats.healthScore}/100 below)
- BOTTOM ROW: ${tokenStats.whaleCount} Whales 🐋 | ${tokenStats.strongCount} Strong 💪 | ${tokenStats.activeCount} Active 🌱 (in white text)
- BOTTOM LEFT: "blackbox.farm/holders" branding

STYLE: Clean, minimal, fintech look. NO busy backgrounds. MAXIMUM TEXT READABILITY. Ultra sharp text.`;

    console.log('Calling Lovable AI for image generation...');

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash-image-preview",
        messages: [
          {
            role: "user",
            content: prompt
          }
        ],
        modalities: ["image", "text"]
      })
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error("AI gateway error:", response.status, errorText);
      
      if (response.status === 429) {
        return new Response(JSON.stringify({ error: "Rate limit exceeded, please try again later" }), {
          status: 429,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      if (response.status === 402) {
        return new Response(JSON.stringify({ error: "AI credits depleted" }), {
          status: 402,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      throw new Error(`AI gateway error: ${response.status}`);
    }

    const aiData = await response.json();
    console.log('AI response received');

    const imageBase64 = aiData.choices?.[0]?.message?.images?.[0]?.image_url?.url;
    
    if (!imageBase64) {
      console.error('No image in AI response:', JSON.stringify(aiData).slice(0, 500));
      throw new Error("No image generated by AI");
    }

    // If just returning base64, do so
    if (returnType === 'base64') {
      return new Response(JSON.stringify({ 
        success: true,
        imageBase64 
      }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Upload to Supabase storage for sharing
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Convert base64 to bytes
    const base64Data = imageBase64.replace(/^data:image\/\w+;base64,/, "");
    const imageBytes = Uint8Array.from(atob(base64Data), (c) => c.charCodeAt(0));

    // NOTE: Bucket must exist. We use the already-provisioned public bucket.
    const bucket = "twitter-assets";
    const now = Date.now();
    const imageFileName = `share-cards/${tokenStats.symbol.toLowerCase()}-${now}.png`;

    const imageBlob = new Blob([imageBytes], { type: "image/png" });

    const { error: uploadError } = await supabase.storage
      .from(bucket)
      .upload(imageFileName, imageBlob, {
        contentType: "image/png",
        upsert: true,
        cacheControl: "3600",
      });

    if (uploadError) {
      console.error("Upload error:", uploadError);
      // Return base64 as fallback
      return new Response(
        JSON.stringify({
          success: true,
          imageBase64,
          note: `Could not upload to storage (${uploadError.message}), returning base64`,
        }),
        {
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        }
      );
    }

    const { data: imagePublicUrl } = supabase.storage.from(bucket).getPublicUrl(imageFileName);

    console.log('Image uploaded successfully:', imagePublicUrl.publicUrl);

    // Create a public HTML "share page" in Storage that contains OG/Twitter meta tags.
    // This is what X/Twitter will crawl to render the image preview.
    const safeSymbol = escapeHtml((tokenStats.symbol || "TOKEN").toUpperCase());
    const title = `Holder Analysis: $${safeSymbol} — BlackBox Farm`;
    const description = `Free holder analysis report for $${safeSymbol}.`;
    const canonical = tokenStats.tokenAddress
      ? `https://blackbox.farm/holders?token=${encodeURIComponent(tokenStats.tokenAddress)}`
      : "https://blackbox.farm/holders";

    const sharePageHtml = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${title}</title>
  <meta name="description" content="${escapeHtml(description)}" />
  <link rel="canonical" href="${escapeHtml(canonical)}" />

  <meta property="og:type" content="website" />
  <meta property="og:title" content="${title}" />
  <meta property="og:description" content="${escapeHtml(description)}" />
  <meta property="og:url" content="${escapeHtml(canonical)}" />
  <meta property="og:image" content="${escapeHtml(imagePublicUrl.publicUrl)}" />
  <meta property="og:image:secure_url" content="${escapeHtml(imagePublicUrl.publicUrl)}" />
  <meta property="og:image:width" content="1200" />
  <meta property="og:image:height" content="628" />

  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="${title}" />
  <meta name="twitter:description" content="${escapeHtml(description)}" />
  <meta name="twitter:image" content="${escapeHtml(imagePublicUrl.publicUrl)}" />

  <style>
    :root { color-scheme: dark; }
    body { margin: 0; font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial; background: #0b0b0f; color: #eaeaf2; }
    main { max-width: 920px; margin: 0 auto; padding: 28px 16px 40px; }
    .card { border: 1px solid rgba(255,255,255,0.10); background: rgba(255,255,255,0.03); border-radius: 16px; overflow: hidden; }
    .header { display:flex; align-items: baseline; justify-content: space-between; gap: 12px; padding: 16px 16px 10px; }
    .kicker { font-size: 12px; opacity: 0.75; letter-spacing: 0.06em; text-transform: uppercase; }
    .title { font-size: 18px; font-weight: 800; }
    img { width: 100%; height: auto; display: block; }
    .footer { display:flex; justify-content: space-between; gap: 10px; padding: 12px 16px 16px; font-size: 13px; opacity: 0.85; }
    a { color: #6ee7b7; text-decoration: none; }
    a:hover { text-decoration: underline; }
  </style>
</head>
<body>
  <main>
    <div class="card">
      <div class="header">
        <div>
          <div class="kicker">BlackBox Farm</div>
          <div class="title">Holder Analysis: $${safeSymbol}</div>
        </div>
        <div class="kicker"><a href="${escapeHtml(canonical)}">blackbox.farm/holders</a></div>
      </div>
      <img src="${escapeHtml(imagePublicUrl.publicUrl)}" alt="Holder analysis share card for $${safeSymbol}" loading="eager" />
      <div class="footer">
        <span>Preview image for social sharing</span>
        <span><a href="${escapeHtml(canonical)}">Open full report →</a></span>
      </div>
    </div>
  </main>
</body>
</html>`;

    let sharePageUrl: string | null = null;
    try {
      const sharePageFileName = `share-pages/${tokenStats.symbol.toLowerCase()}-${now}.html`;
      const pageBlob = new Blob([sharePageHtml], { type: "text/html" });

      const { error: pageUploadError } = await supabase.storage
        .from(bucket)
        .upload(sharePageFileName, pageBlob, {
          contentType: "text/html",
          upsert: true,
          cacheControl: "3600",
        });

      if (pageUploadError) {
        console.error("Share page upload error:", pageUploadError);
      } else {
        const { data: sharePagePublicUrl } = supabase.storage.from(bucket).getPublicUrl(sharePageFileName);
        sharePageUrl = sharePagePublicUrl.publicUrl;
        console.log("Share page uploaded successfully:", sharePageUrl);
      }
    } catch (e) {
      console.error("Failed to create share page:", e);
    }

    return new Response(
      JSON.stringify({
        success: true,
        imageUrl: imagePublicUrl.publicUrl,
        sharePageUrl,
        imageBase64,
      }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );

  } catch (error) {
    console.error('Error generating share card:', error);
    return new Response(JSON.stringify({ 
      error: error instanceof Error ? error.message : 'Unknown error' 
    }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
