/**
 * Strip EXIF data from an image blob by re-encoding through canvas,
 * and generate a short human-readable filename.
 */

const ADJECTIVES = [
  'bold', 'sharp', 'dark', 'vivid', 'clean', 'prime', 'raw', 'core',
  'deep', 'swift', 'bright', 'solid', 'keen', 'fresh', 'stark',
];

const NOUNS = [
  'signal', 'pulse', 'frame', 'lens', 'view', 'shot', 'flash', 'grid',
  'drop', 'spark', 'edge', 'bloom', 'trace', 'mark', 'glow',
];

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

/** Generate a short, human-style image name like "bold-signal-hero" */
export function generateImageName(context: 'hero' | 'inline', articleTitle?: string): string {
  const slug = articleTitle
    ? articleTitle
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-|-$/g, '')
        .slice(0, 24)
        .replace(/-$/, '')
    : '';

  const flair = `${pick(ADJECTIVES)}-${pick(NOUNS)}`;
  const suffix = context === 'hero' ? 'hero' : 'inline';

  return slug
    ? `${slug}-${flair}-${suffix}`
    : `${flair}-${suffix}`;
}

/**
 * Re-encode an image blob through a canvas to strip all EXIF/metadata,
 * then inject minimal IPTC-style copyright info via a comment marker.
 * 
 * Since canvas.toBlob strips all metadata by default, this effectively
 * removes EXIF, GPS, camera info, and original creator data.
 * 
 * Returns a clean JPEG blob.
 */
export async function stripExifAndBrand(blob: Blob): Promise<Blob> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = img.naturalWidth;
      canvas.height = img.naturalHeight;
      const ctx = canvas.getContext('2d');
      if (!ctx) {
        resolve(blob); // fallback
        return;
      }
      ctx.drawImage(img, 0, 0);

      canvas.toBlob(
        (cleanBlob) => {
          if (!cleanBlob) {
            resolve(blob);
            return;
          }

          // Inject a minimal XMP/comment with our copyright into the JPEG
          injectCopyright(cleanBlob).then(resolve).catch(() => resolve(cleanBlob));
        },
        'image/jpeg',
        0.92
      );
    };
    img.onerror = () => resolve(blob);
    img.src = URL.createObjectURL(blob);
  });
}

/**
 * Inject a JPEG COM (comment) marker with copyright info.
 * This is the simplest way to embed ownership without external libs.
 */
async function injectCopyright(blob: Blob): Promise<Blob> {
  const copyright = [
    `Copyright (c) ${new Date().getFullYear()} BlackBox Farm`,
    `Website: https://blackbox.farm`,
    `Source: BlackBox Farm Intelligence Platform`,
    `All rights reserved.`,
  ].join('\n');

  const buf = await blob.arrayBuffer();
  const src = new Uint8Array(buf);

  // JPEG starts with FF D8. Insert COM marker (FF FE) right after SOI.
  if (src[0] !== 0xFF || src[1] !== 0xD8) {
    return blob; // not a JPEG
  }

  const commentBytes = new TextEncoder().encode(copyright);
  const len = commentBytes.length + 2; // +2 for length field itself

  // Build COM marker: FF FE + 2-byte length + comment
  const comMarker = new Uint8Array(4 + commentBytes.length);
  comMarker[0] = 0xFF;
  comMarker[1] = 0xFE;
  comMarker[2] = (len >> 8) & 0xFF;
  comMarker[3] = len & 0xFF;
  comMarker.set(commentBytes, 4);

  // Splice: SOI (2 bytes) + COM marker + rest of JPEG
  const result = new Uint8Array(2 + comMarker.length + (src.length - 2));
  result.set(src.subarray(0, 2), 0);
  result.set(comMarker, 2);
  result.set(src.subarray(2), 2 + comMarker.length);

  return new Blob([result], { type: 'image/jpeg' });
}

/**
 * Inject PNG tEXt chunks (Title, Author, Copyright, Source, Software) into a
 * PNG blob. These are the standard PNG textual-metadata keywords and are
 * preserved by most image viewers and CDNs.
 *
 * Chunk format: length(4) | type(4) | data | crc(4)
 * tEXt data: keyword \0 text  (Latin-1)
 */
export async function injectPngCopyright(blob: Blob): Promise<Blob> {
  const buf = await blob.arrayBuffer();
  const src = new Uint8Array(buf);

  // PNG signature: 89 50 4E 47 0D 0A 1A 0A
  const sig = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];
  for (let i = 0; i < sig.length; i++) {
    if (src[i] !== sig[i]) return blob; // not a PNG
  }

  const year = new Date().getFullYear();
  const entries: Array<[string, string]> = [
    ['Title', 'BlackBox Farm — Bubble Map Snapshot'],
    ['Author', 'BlackBox Farm Intelligence'],
    ['Copyright', `Copyright (c) ${year} BlackBox Farm. All rights reserved.`],
    ['Source', 'https://blackbox.farm/bubblemap'],
    ['Software', 'BlackBox Farm Bubble Map'],
    ['Comment', 'Generated by https://blackbox.farm — do not redistribute without attribution.'],
  ];

  const chunks: Uint8Array[] = [];
  for (const [keyword, text] of entries) {
    chunks.push(buildTextChunk(keyword, text));
  }

  // Insert chunks immediately after the PNG signature (before IHDR). Most
  // decoders accept ancillary chunks anywhere before IEND, but the safest
  // legal location for tEXt is after IHDR. Find IHDR end and splice there.
  // PNG: sig(8) | length(4) IHDR(4) data(13) crc(4) = sig + 25 bytes for IHDR.
  const insertAt = 8 + 4 + 4 + 13 + 4; // = 33
  if (src.length < insertAt) return blob;

  const totalChunkLen = chunks.reduce((a, c) => a + c.length, 0);
  const out = new Uint8Array(src.length + totalChunkLen);
  out.set(src.subarray(0, insertAt), 0);
  let off = insertAt;
  for (const c of chunks) {
    out.set(c, off);
    off += c.length;
  }
  out.set(src.subarray(insertAt), off);

  return new Blob([out], { type: 'image/png' });
}

function buildTextChunk(keyword: string, text: string): Uint8Array {
  const enc = new TextEncoder();
  // tEXt uses Latin-1; TextEncoder is UTF-8 but ASCII is identical, and our
  // strings are ASCII-only, so this is safe.
  const kw = enc.encode(keyword);
  const txt = enc.encode(text);
  const data = new Uint8Array(kw.length + 1 + txt.length);
  data.set(kw, 0);
  data[kw.length] = 0x00;
  data.set(txt, kw.length + 1);

  const type = enc.encode('tEXt');
  const chunk = new Uint8Array(4 + 4 + data.length + 4);
  // length (big-endian)
  const len = data.length;
  chunk[0] = (len >>> 24) & 0xff;
  chunk[1] = (len >>> 16) & 0xff;
  chunk[2] = (len >>> 8) & 0xff;
  chunk[3] = len & 0xff;
  chunk.set(type, 4);
  chunk.set(data, 8);

  // CRC32 over type + data
  const crcInput = new Uint8Array(type.length + data.length);
  crcInput.set(type, 0);
  crcInput.set(data, type.length);
  const crc = crc32(crcInput);
  const crcOff = 8 + data.length;
  chunk[crcOff] = (crc >>> 24) & 0xff;
  chunk[crcOff + 1] = (crc >>> 16) & 0xff;
  chunk[crcOff + 2] = (crc >>> 8) & 0xff;
  chunk[crcOff + 3] = crc & 0xff;
  return chunk;
}

// Standard CRC32 (PNG polynomial)
let CRC_TABLE: Uint32Array | null = null;
function crc32(bytes: Uint8Array): number {
  if (!CRC_TABLE) {
    CRC_TABLE = new Uint32Array(256);
    for (let n = 0; n < 256; n++) {
      let c = n;
      for (let k = 0; k < 8; k++) {
        c = (c & 1) ? (0xedb88320 ^ (c >>> 1)) : (c >>> 1);
      }
      CRC_TABLE[n] = c >>> 0;
    }
  }
  let crc = 0xffffffff;
  for (let i = 0; i < bytes.length; i++) {
    crc = (CRC_TABLE[(crc ^ bytes[i]) & 0xff] ^ (crc >>> 8)) >>> 0;
  }
  return (crc ^ 0xffffffff) >>> 0;
}
