import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { Resend } from 'npm:resend@2.0.0';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface PatternAlert {
  id: string;
  user_id: string;
  alert_type: string;
  severity: string;
  title: string;
  description: string;
  metadata: any;
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
  const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
  const resendApiKey = Deno.env.get('RESEND_API_KEY');
  const telegramBotToken = Deno.env.get('TELEGRAM_BOT_TOKEN');
  
  const supabase = createClient(supabaseUrl, supabaseServiceKey);

  try {
    const { alert_id, alert } = await req.json();

    // Get the alert if ID provided
    let patternAlert: PatternAlert;
    if (alert_id) {
      const { data, error } = await supabase
        .from('mega_whale_pattern_alerts')
        .select('*')
        .eq('id', alert_id)
        .single();
      
      if (error || !data) throw new Error('Alert not found');
      patternAlert = data;
    } else if (alert) {
      patternAlert = alert;
    } else {
      throw new Error('No alert provided');
    }

    // Get user's notification config
    const { data: config } = await supabase
      .from('mega_whale_alert_config')
      .select('*')
      .eq('user_id', patternAlert.user_id)
      .single();

    const results = {
      email_sent: false,
      telegram_sent: false,
      browser_notified: false
    };

    // Send Email
    if (config?.notify_email && config?.email_address && resendApiKey) {
      try {
        const resend = new Resend(resendApiKey);
        const severityEmoji = {
          critical: '🚨',
          high: '⚠️',
          medium: '📊',
          low: 'ℹ️'
        }[patternAlert.severity] || '📊';

        await resend.emails.send({
          from: 'Mega Whale Alerts <alerts@resend.dev>',
          to: [config.email_address],
          subject: `${severityEmoji} ${patternAlert.title}`,
          html: `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
              <h2 style="color: ${patternAlert.severity === 'critical' ? '#ef4444' : '#f59e0b'};">
                ${severityEmoji} ${patternAlert.title}
              </h2>
              <p style="color: #374151; font-size: 16px;">${patternAlert.description}</p>
              <div style="background: #f3f4f6; padding: 16px; border-radius: 8px; margin-top: 16px;">
                <h4 style="margin: 0 0 8px 0; color: #1f2937;">Alert Details</h4>
                <p style="margin: 0; color: #6b7280; font-size: 14px;">
                  Type: <strong>${patternAlert.alert_type}</strong><br>
                  Severity: <strong>${patternAlert.severity.toUpperCase()}</strong><br>
                  Time: <strong>${new Date().toISOString()}</strong>
                </p>
                ${patternAlert.metadata?.token_mint ? `
                  <p style="margin: 8px 0 0 0; color: #6b7280; font-size: 14px;">
                    Token: <code style="background: #e5e7eb; padding: 2px 6px; border-radius: 4px;">${patternAlert.metadata.token_mint}</code>
                  </p>
                ` : ''}
              </div>
              <p style="color: #9ca3af; font-size: 12px; margin-top: 24px;">
                This alert was generated by your Mega Whale monitoring system.
              </p>
            </div>
          `,
        });
        results.email_sent = true;
        console.log(`[NOTIFIER] Email sent to ${config.email_address}`);
      } catch (e) {
        console.error('[NOTIFIER] Email error:', e);
      }
    }

    // Send Telegram
    if (config?.notify_telegram && config?.telegram_chat_id && telegramBotToken) {
      try {
        const severityEmoji = {
          critical: '🚨',
          high: '⚠️',
          medium: '📊',
          low: 'ℹ️'
        }[patternAlert.severity] || '📊';

        const title = patternAlert.title || patternAlert.pattern_type || 'Alert';
        const description = patternAlert.description || '';
        const alertType = patternAlert.alert_type || patternAlert.pattern_type || 'unknown';

        const message = `${severityEmoji} *${escapeMarkdown(title)}*

${escapeMarkdown(description)}

*Type:* \`${alertType}\`
*Severity:* ${(patternAlert.severity || 'info').toUpperCase()}
${patternAlert.metadata?.token_mint ? `*Token:* \`${patternAlert.metadata.token_mint}\`` : ''}
${patternAlert.metadata?.wallets_involved ? `*Wallets:* ${patternAlert.metadata.wallets_involved}` : ''}`;

        const response = await fetch(
          `https://api.telegram.org/bot${telegramBotToken}/sendMessage`,
          {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              chat_id: config.telegram_chat_id,
              text: message,
              parse_mode: 'Markdown'
            })
          }
        );

        if (response.ok) {
          results.telegram_sent = true;
          console.log(`[NOTIFIER] Telegram sent to ${config.telegram_chat_id}`);
        }
      } catch (e) {
        console.error('[NOTIFIER] Telegram error:', e);
      }
    }

    // Update alert as notified
    if (alert_id) {
      await supabase
        .from('mega_whale_pattern_alerts')
        .update({
          is_notified_email: results.email_sent,
          is_notified_telegram: results.telegram_sent,
          is_notified_browser: results.browser_notified
        })
        .eq('id', alert_id);
    }

    return new Response(
      JSON.stringify({ success: true, results }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('[NOTIFIER] Error:', error);
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});

function escapeMarkdown(text: string | undefined | null): string {
  if (!text) return '';
  // Only escape characters that break Telegram Markdown: * _ ` [
  return String(text).replace(/([*_`\[])/g, '\\$1');
}