-- Insert alert configuration for user
INSERT INTO mega_whale_alert_config (
  user_id,
  notify_email,
  email_address,
  notify_telegram,
  telegram_chat_id,
  notify_browser,
  funding_burst_count,
  funding_burst_window_minutes,
  coordinated_buy_count,
  coordinated_buy_window_minutes,
  profit_taking_threshold_percent,
  auto_buy_on_mint,
  auto_buy_amount_sol,
  auto_buy_wait_for_buys,
  auto_buy_max_wait_minutes
) VALUES (
  '39fc11c3-5a61-4aa1-9bc5-327c101b266e',
  true,
  'wilsondavid@live.ca',
  true,
  '7045582884',
  true,
  3,
  5,
  3,
  10,
  50,
  true,
  0.1,
  5,
  10
) ON CONFLICT (user_id) DO UPDATE SET
  notify_email = EXCLUDED.notify_email,
  email_address = EXCLUDED.email_address,
  notify_telegram = EXCLUDED.notify_telegram,
  telegram_chat_id = EXCLUDED.telegram_chat_id,
  notify_browser = EXCLUDED.notify_browser,
  funding_burst_count = EXCLUDED.funding_burst_count,
  funding_burst_window_minutes = EXCLUDED.funding_burst_window_minutes,
  coordinated_buy_count = EXCLUDED.coordinated_buy_count,
  coordinated_buy_window_minutes = EXCLUDED.coordinated_buy_window_minutes,
  profit_taking_threshold_percent = EXCLUDED.profit_taking_threshold_percent,
  auto_buy_on_mint = EXCLUDED.auto_buy_on_mint,
  auto_buy_amount_sol = EXCLUDED.auto_buy_amount_sol,
  auto_buy_wait_for_buys = EXCLUDED.auto_buy_wait_for_buys,
  auto_buy_max_wait_minutes = EXCLUDED.auto_buy_max_wait_minutes,
  updated_at = now();