-- Add enrichment columns to twitter_accounts
ALTER TABLE public.twitter_accounts 
ADD COLUMN IF NOT EXISTS twitter_id TEXT,
ADD COLUMN IF NOT EXISTS tweet_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS likes_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS listed_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS media_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS join_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS is_protected BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS last_enriched_at TIMESTAMPTZ;