import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { InputOTP, InputOTPGroup, InputOTPSlot } from '@/components/ui/input-otp';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Loader2, Shield } from 'lucide-react';
import { Checkbox } from '@/components/ui/checkbox';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';

interface OTPVerificationProps {
  email: string;
  onVerificationSuccess: (session: any) => void;
  onBack: () => void;
}

export const OTPVerification = ({ email, onVerificationSuccess, onBack }: OTPVerificationProps) => {
  const [otpCode, setOtpCode] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [rememberDevice, setRememberDevice] = useState(false);
  const { toast } = useToast();

  const verifyOTP = async () => {
    if (otpCode.length !== 6) {
      setError('Please enter a 6-digit code');
      return;
    }

    setLoading(true);
    setError('');

    try {
      const { data, error } = await supabase.functions.invoke('verify-2fa-login', {
        body: { 
          email, 
          totpCode: otpCode,
          rememberDevice 
        }
      });

      if (error) throw error;

      if (data.success) {
        toast({
          title: "Login successful",
          description: "You have been authenticated successfully.",
        });
        onVerificationSuccess(data.session);
      } else {
        setError(data.message || 'Invalid verification code');
      }
    } catch (error: any) {
      console.error('OTP verification error:', error);
      setError(error.message || 'Failed to verify code');
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card className="w-full max-w-md mx-auto tech-border">
      <CardHeader className="text-center space-y-2">
        <div className="mx-auto w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center">
          <Shield className="w-6 h-6 text-primary" />
        </div>
        <CardTitle className="text-xl">Two-Step Verification</CardTitle>
        <p className="text-sm text-muted-foreground">
          For added security, please enter the One Time Password (OTP) generated by your Authenticator App
        </p>
      </CardHeader>

      <CardContent className="space-y-6">
        <div className="space-y-2">
          <label className="text-sm font-medium">Enter OTP:</label>
          <InputOTP
            maxLength={6}
            value={otpCode}
            onChange={setOtpCode}
            className="w-full"
          >
            <InputOTPGroup className="w-full justify-center">
              <InputOTPSlot index={0} />
              <InputOTPSlot index={1} />
              <InputOTPSlot index={2} />
              <InputOTPSlot index={3} />
              <InputOTPSlot index={4} />
              <InputOTPSlot index={5} />
            </InputOTPGroup>
          </InputOTP>
        </div>

        <div className="flex items-center space-x-2">
          <Checkbox
            id="remember-device"
            checked={rememberDevice}
            onCheckedChange={(checked) => setRememberDevice(checked === true)}
          />
          <label
            htmlFor="remember-device"
            className="text-sm text-muted-foreground cursor-pointer"
          >
            Don't require OTP on this browser
          </label>
        </div>

        {error && (
          <Alert variant="destructive">
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        <div className="space-y-3">
          <Button
            onClick={verifyOTP}
            disabled={loading || otpCode.length !== 6}
            className="w-full tech-button"
          >
            {loading ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Verifying...
              </>
            ) : (
              'Sign in'
            )}
          </Button>

          <Button
            variant="outline"
            onClick={onBack}
            className="w-full"
            disabled={loading}
          >
            Back to Login
          </Button>
        </div>

        <div className="text-center">
          <Button
            variant="link"
            className="text-sm text-primary"
            onClick={() => toast({
              title: "Didn't receive the OTP?",
              description: "Check your authenticator app and ensure the time is synchronized.",
            })}
          >
            Didn't receive the OTP?
          </Button>
        </div>
      </CardContent>
    </Card>
  );
};